ADDMatrix_flag: true
camera_info_topic_color: /camera/color/camera_info
camera_info_topic_depth: /camera/depth/camera_info
combine_particle_depth_mask_flag: false
convolution_size: 0
debug_depth_img_flag: false
depth_diff_value_0_1_alpha: 0.8
depth_diff_value_0_1_flag: true
depth_diff_value_0_1_threshold: 0.03
depth_image_cut_flag: false
depth_mask_flag: false
dope_flag: true
err_file: rayTracing
farVal: 3
gazebo_flag: false
height: 480
locate_camera_flag: ar
nearVal: 0.3
object_name_list:
- cracker
- soup
object_num: 2
obstacles_ori:
- - 1.0
  - 0.0
  - 0.0
  - 1.0
obstacles_pos:
- - 0.8315
  - 0.215
  - 0.14765408574692843
optitrack_flag: true
ortho_to_persp_flag: true
other_obj_num: 0
oto_name_list:
- base_of_cracker
- fish_can
otob_name_list:
- cracker_obstacle
- fish_can
panda_robot_link_number: 11
particle_num: 70
pb_render_flag: false
persp_to_ortho_flag: false
pick_particle_rate: 0.0
print_score_flag: false
ray_tracing_type: multiray
remove_min_max_flag: true
robot_num: 1
run_alg_flag: PBPF
running_model: PBPF_D
show_particle_depth_image_to_point_cloud_flag: true
show_ray: false
sim_real_world_flag: true
task_flag: '2'
update_style_flag: time
use_convolution_flag: false
version: multiray
vk_render_flag: true
width: 848
