dope_flag: true
err_file: rayTracing
gazebo_flag: false
object_name_list:
- cracker
- potted_meat
object_num: 1
other_obj_num: 1
oto_name_list:
- base_of_cracker
- fish_can
otob_name_list:
- cracker_obstacle
- fish_can
particle_num: 70
pick_particle_rate: 0.05
robot_num: 1
run_alg_flag: PBPF
task_flag: '1'
update_style_flag: time
version: old
